apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "book-store.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "book-store.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "book-store.name" . }}
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.image.app.repository }}:{{ .Values.image.app.tag}}
        imagePullPolicy: {{ .Values.image.app.pullPolicy }}
        ports:
        - containerPort: 3000
