apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "book-store.fullname" . }}-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "book-store.name" . }}-mongodb
  template:
    metadata:
      labels:
        app: {{ include "book-store.name" . }}-mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.image.mongodb.repository }}:{{ .Values.image.mongodb.tag}}
        imagePullPolicy: {{ .Values.image.mongodb.pullPolicy }}
        ports:
        - containerPort: 27017