version: 2.1
orbs:
  docker: circleci/docker@2.4.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  # https://circleci.com/developer/images/image/cimg/go
  build:
    docker:
      - image: cimg/go:1.21.5
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USER --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            make docker-build IMG=$BOOKSTORE_OPERATOR_IMG
            make docker-push IMG=$BOOKSTORE_OPERATOR_IMG
  # https://circleci.com/developer/orbs/orb/circleci/kubernetes
  deploy:
    docker:
    - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Setup Kubeconfig
          command: echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config
      - run:
          name: Install Helm 3
          command: |
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - run:
          name: Deploy Kubernetes Artifacts to Cluster
          command: |
            make deploy

workflows:
  workflow:
    jobs:
      - build
      - deploy
    requires:
      - build