# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    working_directory: /go/src/manager
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: golang:1.21
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set the tag for the docker image
          command:  echo 'export TAG=$(cat VERSION)-$CIRCLE_BUILD_NUM' >> $BASH_ENV
      - run:
          name: Build the docker image
          command: docker build . -t ${DOCKER_USRE}/bookstore-operator-go:$TAG
      - run:
          name: Login to docker Hub
          command: $(docker login -u ${DOCKER_USRE} -p ${DOCKER_HUB_PASSWD} docker.io)
      - run: 
          name: Push the image to docker Hub
          command: docker push ${DOCKER_USRE}/bookstore-operator-go:$TAG
  deploy:
    working_directory: /tmp/workspace
    docker:
      - image: golang:1.21
    steps:
      - checkout
      - run:
          name: Upgrade the cluster
          command: export TZ=Europe/Minsk && sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > sudo  /etc/timezone && sudo apt-get update
      - run:
          name: Install kubectl
          command: sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl && sudo chmod +x /usr/local/bin/kubectl
      - run:
          name: Configure kubeconfig
          command: echo ${KUBECONFIG_DATA} | base64 --decode > $HOME/.kube/config
      - run:
          name: Install helm
          command: sudo curl -L https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz | tar xz && sudo mv linux-amd64/helm /bin/helm && sudo rm -rf linux-amd64

# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  workflow:
    jobs:
      - build
      - deploy
